FROM amazoncorretto:8-alpine

LABEL maintainer="datax-cloud"

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apk add --no-cache curl

WORKDIR /app

COPY jars/datax-eureka.jar app.jar

EXPOSE 8610

ENV JAVA_OPTS="-Xms256m -Xmx512m"
ENV EUREKA_IP=localhost

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Deureka.instance.ip-address=$EUREKA_IP -jar app.jar"]
