FROM amazoncorretto:8-alpine

LABEL maintainer="datax-cloud"

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apk add --no-cache curl

WORKDIR /app

COPY jars/datax-gateway.jar app.jar

EXPOSE 8612

ENV JAVA_OPTS="-Xms256m -Xmx512m"
ENV EUREKA_SERVER=http://localhost:8610/eureka
ENV CONFIG_SERVER=localhost

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Deureka.client.service-url.defaultZone=$EUREKA_SERVER -Dspring.cloud.config.discovery.service-id=datax-config -jar app.jar"]
