FROM amazoncorretto:8-alpine

LABEL maintainer="datax-cloud"

ARG SERVICE_NAME
ARG SERVICE_PORT=8080

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apk add --no-cache curl

WORKDIR /app

COPY jars/${SERVICE_NAME}.jar app.jar

EXPOSE ${SERVICE_PORT}

ENV JAVA_OPTS="-Xms256m -Xmx512m"
ENV EUREKA_SERVER=http://localhost:8610/eureka
ENV CONFIG_SERVER=localhost
ENV MYSQL_HOST=localhost
ENV REDIS_HOST=localhost
ENV RABBITMQ_HOST=localhost

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Deureka.client.service-url.defaultZone=$EUREKA_SERVER -jar app.jar"]
